name: "[live] deploy latest"

on:
  push:
    branches: [main]

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Connect to Server
        run: npm run deploy

      # - name: Deploy using ssh
      #   run: 
      #     script: |
      #     7SHv3us86QtGd6uV
      #     cd /root/hakaton_backend/
      #     git pull origin main
      #     npm ci
      #     pm2 restart app.js
